listen:
  name: Zuhören
  description: >-
    Startet die Sprachaufnahme über das Wyoming-Mikrofon und gibt die Antwort
    über den konfigurierten Media Player aus.
  fields:
    entry_id:
      name: Config Entry ID
      description: >-
        Die ID des Konfigurationseintrags. Nur nötig wenn mehrere Instanzen
        konfiguriert sind.
      required: false
      example: "abcdef1234567890"
      selector:
        text:
